module.exports = [////Start Hard Words
'Contrived: fake, created, forced,strained,studied,artificial.created or arranged in a way that seems artificial and unrealistic."the ending of the novel is too pat and contrived"',
'Vexed, irritated, annoyed.(of a problem or issue) difficult and much debated; problematic."the relationship is becoming strained over the vexed question of money".annoyed, frustrated, or worried."I am very vexed with you!"',
'Dwell, inhabit,vivir en, habitar,to live in a place or in a particular way, "She dwelt in remote parts of Asia for many years"',
'Deference, polite, humble, with respect, humble submission and respect."he addressed her with the deference due to age"',
'Wry,droll, raro, irónico, Dry, sarcástico,using or expressing dry, especially mocking, humor."a wry smile".(of a person\'s face or features) twisted into an expression of disgust, disappointment, or annoyance.',
'Poignant, affecting, emotionally moving. "a poignant reminder of the passing of time"."The photograph awakens poignant memories of happier days"',
'Placate, satisfy, appease, to appease or pacify, especially by concessions or conciliatory gestures."he has tried to placate his critics within the party"."they attempted to placate the students with promises"."my apology did nothing to placate her"',
'Rescind, revoke, repeal, to cancel,take back, cancel."she refused to rescind the order"',
'Succinct, concise, briefly, short, laconic, (especially of something written or spoken) briefly and clearly expressed."use short, succinct sentences"',
'Wicked, morally wrong, evil or morally wrong."a wicked and unscrupulous politician". intended to or capable of harming someone or something. "he should be punished for his wicked driving"',
'Enmity, acrimony,deep feelings of dislike or hostility,enemistad',
'Acrimony, bitter or hostile attitude or feelings',
'Accord, agreement or harmony',
'Embellishment, embellecimiento, the act of adding decorative or unnecessary details to something',
'Outskirts, outlying areas',
'Hatred, odio',
'Disguised, unrecognizable, camouflaged',
'Ramshackle,State of disrepair, neglect ',
'Steadfast, firme , resuelto ',
'Unflagging, continuing without tiring or weakness ',
'Cursory, little attention to detail, superficial',
'Chronic, habitual ',
'Trepidation, caution ',
'vindictive, vengeful, vengativo',
'compendious, laconic, use few words',
'Bewilder, confuse',
'Soothing, calming',
'Flattering, complimentary, halagador ',
'Abrogate, repeal, do away with ',
'Substantial, sizable ',
'Incident, occurrence',
'abate, reduce in amount or degree to lessen',
'Parity, equality, equal in amount or status',
'oath, promise, juramento ',
/////////////End Hard Words
'Scarce, rare',
'Apathetic, no emotion, showing no interest ',
'Verbose, long-winded, talk with too many words',
'Ephemeral,efímera, corto periodo de tiempo',
'Fleeting, fugaz, ephemeral , short time',
'Onerous, difficult, pesado ',
'Derelict, abandoned ',
'hinder, obstaculizar',
'Fustian, pompous or Inflated language',
'Phony, no genuine, fraudulent ',
'Cunning, clever',
'Wary, Cuidadoso',
'Endemic, native',
'Conundrum, puzzle',
'Benevolent, kind',
'Augment, enhance',
'Lassitude, fatigue',
'Propinquity, Proximity',
'Emanate, idea, proposal, exude',
'Exude, desprender ',
'Belligerent, aggressive',
'Irascible, irritable ',
'Ameliorate, improve ',
'Obtuse, torpe',
'Dull, aburrido ',
'Wisdom, sabiduría',
'Defray, pay',
'Humble, meek',
'Defiance, desafío',
'Irate, indignado, furioso',
'Slight, weak',
'Nominal, small',
'Intrepid, brave, bold',
'Exert, try hard, make use of, ejercer',
'Scold, reprender, reprimand, regañar ',
'Linger, tardar en marcharse ',
'Precocious, advanced mentally ',
'Opulent, luxurious',
'Brevity, briefness, shortness of time',
'Vociferous, vehement, express in a loud voice ',
'Bolted, sprinted, ran quickly',
'toiled, worked',
'gregarious, sociable',
'instigate, initiate',
'erode, wear away',
'wither, wilt, dry up',
'enliven, energize',
'Stranded, varado',
'gaunt, extremely thin',
'candor, honesty',
'stubborn, obstinate',
'unruly, not submissive',
'afflicted, caused pain',
'livelihood, career',
'promising, hopeful',
'undertake, take a task upon oneself, emprender',
'appealing, attractive',
'wander, to roam',
'boast, brag, presume',
'inquire, ask',
'rebuke, reprimand, reprender',
'defiance, rebelliousness',
'Adrift, not attached',
'Diminish, become Small',
'Boisterous, clamorous, loud, noisy',
'Prolific, profuse, creating a large number of things ',
'Empirical, verifiable by observation, experiment, experience',
'Unblemished, flawless, without flaws or imperfections, perfect, complete',
'Impaired, damaged, made worse',
'Sporadic, happening infrequently or infrequently',
'Unorthodox, not conforming to the traditional or accepted ways of doing something',
'Enraged, very angry '
    ];